# 예외 포함과 스택 트레이스

직접 Exception 을 생성 할 때 생성자를 단순히 message 만 출력되게 생성하지 말고

```java
    // RuntimeException 로 변경
    static class RuntimeConnectException extends RuntimeException{
        // 단순하게 Param 에 작성된 exception message 만 출력해줌
        public RuntimeConnectException(String message) {
            super(message);
        }
    }
```

throwable cause 로 생성자를 만들어주게되면 

```java
    // RuntimeException 로 변경
    static class RuntimeSQLException extends RuntimeException {

        // 이전 예외까지 포함해서 Param Exception message 를 출력해줌
        // root cause 까지 출력이 되는 method 이다.
        public RuntimeSQLException(Throwable cause) {
            super(cause);
        }
    }
```

예외를 처리할 때 이전에 발생했던 원인 에러의 message 까지 같이 출력이 된다.

```java
static class Repository{
        public void call() {
            try {
                runSQL();
            } catch (SQLException e) {
                // RuntimeSQLException 을 만들 때
                // Cause Throwable 로 만들었기 때문에
                // 예외가 발생하면 이전 예외인 SQLException 의 설명이 출력되고
                // 속성은 RuntimeException 을 상속받아 Throw 를 선언하지 안아도 되게 변경되었다.
                // param 의 e 가 기존 exception 이다.
                throw new RuntimeSQLException(e);
            }
        }

        // exception 의 원인
        public void runSQL() throws SQLException {
            throw new SQLException("SQL Exception");
        }
    }
```

호출해서 exception 을 처리하면 로그를 확인할 수 있다.

```java
   @Test
    void printEx() {
        Controller controller = new Controller();
        try {
            controller.request();
        // Repository 에서 던진 exception 을 잡아서 로그로 남김
        } catch (Exception e) {
            log.info("ex", e);
        }
    }
```

log 의 “ex” 뒤에 Runtime SQLException 에 대한 message 가 나오고

그 뒤에 SQLException 에 대한 message 가 출력됨

<img width="534" alt="s6511" src="https://user-images.githubusercontent.com/115536240/215918666-673f6eec-90f6-45f7-8399-79c3c7282d8c.png">

만약 단순하게 직접 생성한 exception 의 message 만 출력하면 아무 정보도 없는 껍떼기 exception 의 message 만 출력되게 된다.

- 가장 밑에 출력되는 Caused by 가 원인이 되는 근본적인 문제의 Message 이고 이 message 를 root cause 라고 부른다.
